# Generated by Django 3.0.8 on 2020-07-15 12:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bids',
            old_name='listing_id',
            new_name='blisting_id',
        ),
        migrations.RenameField(
            model_name='comments',
            old_name='listing_id',
            new_name='clisting_id',
        ),
        migrations.RenameField(
            model_name='watchlist',
            old_name='listing_id',
            new_name='wlisting_id',
        ),
    ]
