# Generated by Django 3.0.8 on 2020-07-17 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0005_auto_20200715_1801'),
    ]

    operations = [
        migrations.AddField(
            model_name='comments',
            name='ctime',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='listing',
            name='ltime',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
